apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rh-devspace-sync-poc
  name: rh-devspace-sync-poc
spec:
  selector:
    matchLabels:
      app: rh-devspace-sync-poc
  template:
    metadata:
      labels:
        app: rh-devspace-sync-poc
    spec:
      containers:
      - image: dockerregistry.example.com/rh-devspace-sync-poc
        name: rh-devspace-sync-poc
